export class Constants {

    public static WEB_SOCKET_RELAY_CLIENT_DATA_STORE_ENTRIES_COMMAND: string = 'DATA-STORE-ENTRIES';

    public static WEB_SOCKET_RELAY_CLIENT_HEARTBEAT_REQUEST_COMMAND: string = 'HEARTBEAT-REQUEST';

    public static WEB_SOCKET_RELAY_CLIENT_INSERT_DATA_STORE_ENTRY_COMMAND: string = 'INSERT-DATA-STORE-ENTRY';

    public static WEB_SOCKET_RELAY_CLIENT_VOTE_REQUEST_COMMAND: string = 'VOTE-REQUEST';

}
